data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", quote = "", na.strings = "?")
data2days <- subset(data, data$Date == "1/2/2007" | data$Date == "2/2/2007")
data2days$Date <- as.Date(data2days$Date, format="%d/%m/%Y")
data2days$DateTime <- paste(data2days$Date, data2days$Time)
data2days$DateTime <- strptime(data2days$DateTime, format = "%Y-%m-%d %H:%M:%S")
par(bg = "transparent")
plot(data2days$DateTime, data2days$Global_active_power, xlab = "", ylab = "Global Active Power (kilowatts)", type = "n")
lines(data2days$DateTime, data2days$Global_active_power)
dev.copy(png, file = "plot2.png", width = 480, height = 480)
dev.off()