data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", quote = "", na.strings = "?")
data2days <- subset(data, data$Date == "1/2/2007" | data$Date == "2/2/2007")
data2days$Date <- as.Date(data2days$Date, format="%d/%m/%Y")
data2days$DateTime <- paste(data2days$Date, data2days$Time)
data2days$DateTime <- strptime(data2days$DateTime, format = "%Y-%m-%d %H:%M:%S")
png(file = "plot4.png", width = 480, height = 480)
par(mfrow = c(2,2), mar = c(4, 4, 2, 2), bg = "transparent")
plot(data2days$DateTime, data2days$Global_active_power, xlab = "", ylab = "Global Active Power", type = "n")
lines(data2days$DateTime, data2days$Global_active_power)
plot(data2days$DateTime, data2days$Voltage, xlab = "datetime", ylab = "Voltage", type = "n")
lines(data2days$DateTime, data2days$Voltage)
plot(data2days$DateTime, data2days$Sub_metering_1, xlab ="", ylab = "Energy sub metering", type ="n")
lines(data2days$DateTime, data2days$Sub_metering_1, col = "black")
lines(data2days$DateTime, data2days$Sub_metering_2, col = "red")
lines(data2days$DateTime, data2days$Sub_metering_3, col = "blue")
legend("topright", lty = c(1,1,1), cex =.92, bty = "n", col =c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(data2days$DateTime, data2days$Global_reactive_power, xlab = "datetime", ylab = "Global_reactive_power", type = "n")
lines(data2days$DateTime, data2days$Global_reactive_power)
dev.off()