data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", quote = "", na.strings = "?")
data2days <- subset(data, data$Date == "1/2/2007" | data$Date == "2/2/2007")
data2days$Date <- as.Date(data2days$Date, format="%d/%m/%Y")
data2days$DateTime <- paste(data2days$Date, data2days$Time)
data2days$DateTime <- strptime(data2days$DateTime, format = "%Y-%m-%d %H:%M:%S")
png(file = "plot3.png", width = 480, height = 480)
par(bg = "transparent")
plot(data2days$DateTime, data2days$Sub_metering_1, xlab ="", ylab = "Energy sub metering", type ="n")
lines(data2days$DateTime, data2days$Sub_metering_1, col = "black")
lines(data2days$DateTime, data2days$Sub_metering_2, col = "red")
lines(data2days$DateTime, data2days$Sub_metering_3, col = "blue")
legend("topright", lty = c(1,1,1), cex =.97, col =c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()